name: Developer Account Keepalive

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  keepalive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create output directory
      run: mkdir -p developer-output

    - name: Login to developer accounts
      env:
        DEVELOPER_ACCOUNTS_JSON: ${{ secrets.DEVELOPER_ACCOUNTS_JSON }}
        SKIP_SCREENSHOTS: 'false'
      run: |
        cd developer-output
        node ../src/developer-login.js

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: developer-keepalive-${{ github.run_number }}-${{ github.run_attempt }}
        path: developer-output/
        retention-days: 7
        if-no-files-found: warn

    - name: Summary
      if: always()
      run: |
        echo "## Developer Account Keepalive Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Run Time:** $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "**Workflow Run:** #${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Parse and display results if summary file exists
        if [ -f "developer-output/developer-summary.json" ]; then
          TOTAL=$(jq -r '.total' developer-output/developer-summary.json)
          SUCCESS=$(jq -r '.successful' developer-output/developer-summary.json)
          FAILED=$(jq -r '.failed' developer-output/developer-summary.json)
          
          echo "### Results:" >> $GITHUB_STEP_SUMMARY
          echo "- **Total Accounts:** $TOTAL" >> $GITHUB_STEP_SUMMARY
          echo "- **✅ Successful:** $SUCCESS" >> $GITHUB_STEP_SUMMARY
          echo "- **❌ Failed:** $FAILED" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Show failures if any
          if [ "$FAILED" -gt 0 ]; then
            echo "### ⚠️ Failed Accounts:" >> $GITHUB_STEP_SUMMARY
            jq -r '.failures[] | "- **\(.account)**: \(.error)"' developer-output/developer-summary.json >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
        fi
        
        echo "### Screenshots Generated:" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        ls -la developer-output/ || echo "No files generated" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY