name: ServiceNow Stats Scraper

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  scrape-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create output directory
      run: mkdir -p stats-output

    - name: Scrape all instances
      env:
        SERVICENOW_INSTANCES_JSON: ${{ secrets.SERVICENOW_INSTANCES_JSON }}
      run: |
        cd stats-output
        node ../src/scrape-stats.js

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: servicenow-stats-${{ github.run_number }}-${{ github.run_attempt }}
        path: stats-output/
        retention-days: 7
        if-no-files-found: warn

    - name: Summary
      if: always()
      run: |
        echo "## ServiceNow Stats Collection Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Run Time:** $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "**Workflow Run:** #${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Parse and display results if summary file exists
        if [ -f "stats-output/stats-summary.json" ]; then
          TOTAL=$(jq -r '.total' stats-output/stats-summary.json)
          SUCCESS=$(jq -r '.successful' stats-output/stats-summary.json)
          FAILED=$(jq -r '.failed' stats-output/stats-summary.json)
          
          echo "### Results:" >> $GITHUB_STEP_SUMMARY
          echo "- **Total Instances:** $TOTAL" >> $GITHUB_STEP_SUMMARY
          echo "- **✅ Successful:** $SUCCESS" >> $GITHUB_STEP_SUMMARY
          echo "- **❌ Failed:** $FAILED" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Show failures if any
          if [ "$FAILED" -gt 0 ]; then
            echo "### ⚠️ Failed Instances:" >> $GITHUB_STEP_SUMMARY
            jq -r '.failures[] | "- **\(.instance)**: \(.error)"' stats-output/stats-summary.json >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
        fi
        
        echo "### Files Generated:" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        ls -la stats-output/ || echo "No files generated" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY